### ISSUE TITLE
use Travis ci and add test coverage 

### ISSUE THREAD

**Issue by lil5** [averageflow/goscope#14]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by averageflow** [comment]
@lil5  First step toward this has been taken, we now have the badge on the README and every commit to master triggers a build, we would like to have added to the Travis file some linting for Go, Javascript, CSS and HTML so that the quality of the project is always kept across all its components.
