### ISSUE TITLE
Transform UI into and SPA

### ISSUE THREAD

**Issue by averageflow** [averageflow/goscope#18]
The goal is to make this more pleasant to use. SPA makes this a smooth and dynamic interface. Suggestions on what to use are welcome, keep in mind we want to keep a small and fast UI with minimal dependencies. Thinking of perhaps using Mithril.js

**Comment by lil5** [comment]
Seem to me like all that's needed is something that keep HTML generation easy and a router

**Comment by lil5** [comment]
https://lit-html.polymer-project.org/
For HTML generation might be nice

**Comment by lil5** [comment]
The router can just be a simple function that changes `window.location` and `window.history.go`


https://developer.mozilla.org/en-US/docs/Web/API/History_API

**Comment by averageflow** [comment]
@lil5 for what it is let us keep it vanilla js, easier for anyone to contribute and dependency free

**Comment by lil5** [comment]
This change might make the go gin app more of a json api with a frontend that consumes it.

Is this the desired path?

This is not a requirement, the possibility is still on the table to keep the server part responsible for the html / css classes used.

**Comment by lil5** [comment]
A JSON API would make tests much easier as it would then only need to deal with JSON instead of parsing HTML.

If the JS needs testing that can be handled by jest if need be.

**Comment by averageflow** [comment]
@lil5 Yes this is the end goal, goscope becoming a data source and us making a nice UI for it. Also this allows the extensibility to a CLI tool or representation of the data in other formats, including simply raw JSON which can later be used by Zabbix or other monitoring agents to detect for example 500 codes in your application

**Comment by lil5** [comment]
@averageflow Seems like you're already almost ready with the rest api

I'll be looking into a refresh of the fe
