### ISSUE TITLE
Add water css light/dark theme possibility

### ISSUE THREAD

**Issue by averageflow** [averageflow/goscope#39]
Add feature that allows changing to dark / light theme. Store that preference in a cookie or in local storage for the next visit.

**Comment by lil5** [comment]
![](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.-VDje78dReAtTj8TW7fR8wHaEK%26pid%3DApi&f=1)
