### ISSUE TITLE
Customize router group for UI

### ISSUE THREAD

**Issue by louis77** [averageflow/goscope#41]
Congrats for this great little project! I like the approach of easy setup and the integrated UI. That's exactly what I was looking for.
However, I would recommend that the UI can be turned of via an env var, like

`GOSCOPE_DISABLE_UI=true`

I would like to run goscope on an API that is deployed on a PaaS and scales to multiple containers. It doesn't make sense to have the UI exposed and there is no way to protect the route. An alternative could be that goscope.Setup() expects a gin router group for the UI path so the group can be configure i.e. by an auth middleware. Example

```go
	router := gin.New()

	goscopeGroup := router.Group("/goscope")
	goscopeGroup.Use(gin.BasicAuth(gin.Accounts{
		"secret_user": "secret_password",
	}))
	goscope.Setup(router, goscopeGroup)
```

What do you think?

**Comment by averageflow** [comment]
I will make the disabling UI a separate issue
