### ISSUE TITLE
Use connection pool

### ISSUE THREAD

**Issue by louis77** [averageflow/goscope#43]
Goscope opens a new connection for every request that is logged:

https://github.com/averageflow/goscope/blob/d56fb93945fd080b459bf62cfbee6cd3a0e2ca58/goscope/logging.go#L61-L63

Testing on our API which has about 1000 requests/min this led quickly to a connection exhaustion even on a MySQL database with 200 available connections. Goscope should use a connection pool, preferably configurable via env var:

`GOSCOPE_DATABASE_CONNECTIONS=16`

**Comment by averageflow** [comment]
Super tip here! Will be adding, unless you want to pr yourself

**Comment by louis77** [comment]
I can do some PRs, sure. Just wanted to make sure if you are open to that.

**Comment by averageflow** [comment]
@louis77 I will work on this project this weekend a bit more and we can tag the new release when things are properly tested.
