### ISSUE TITLE
Url field too small (mysql)

### ISSUE THREAD

**Issue by louis77** [averageflow/goscope#44]
In the mysql model setup the `url` field is sized with 255 characters. This is far too short for some use cases:

https://github.com/averageflow/goscope/blob/d56fb93945fd080b459bf62cfbee6cd3a0e2ca58/setup/mysql.sql#L23

The "common" maximum for URLs is about 2000 characters (even 8000 characters according to RFC). 
Here is a great article about that:
https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

The maximum row size in MySQL 5 is about 64k excluding variable-length fields like `LONGTEXT`. So I would say that the field could easily be extended to a bigger size.

**Comment by averageflow** [comment]
Good call on this, will be changing it
