### ISSUE TITLE
UI: Add search mode filters

### ISSUE THREAD

**Issue by louis77** [averageflow/goscope#45]
It would be great for the UI to provide a way to filter requests by status code class, i.e.

1. 2xx 
2. 3xx
3. 4xx
4. 5xx

**Comment by averageflow** [comment]
Will be adding this weekend

**Comment by averageflow** [comment]
BUMP: haven't had time to add this, will do when possible, since is a good feature. I am expanding it with some more.

**Comment by averageflow** [comment]
TODO: Add date filter, Add status code filter

**Comment by lil5** [comment]
Status code filter is already implemented as dark code in the frontend, This will be a nice small addon after #53 is merged

**Comment by averageflow** [comment]
I would like to see the status one with the current implementation @lil5

**Comment by averageflow** [comment]
A better way to filter on certain columns will be implemented, this will be more correct now, and more flexible, since we do not use Vue.js anymore I also find it cleaner.
