### ISSUE TITLE
Use an sql query builder (goqu)

### ISSUE THREAD

**Issue by lil5** [averageflow/goscope#55]
https://github.com/doug-martin/goqu

This has the benefits of still being in control of the sql statements with no increase in complexity.

I found it unnerving how much string interpolation I had to add for the, optional, filter to work.

**Comment by lil5** [comment]
@averageflow I'm interested in your thoughts on the matter as goqu seems to work slightly different than the standard orm that has haunted you and I in the past.

**Comment by lil5** [comment]
This will also fix some of the linting errors

**Comment by averageflow** [comment]
I will not agree to this @lil5 I think it is a cool project but the problem I see is you end up more time learning the 3rd party package than SQL.
